### PR TITLE
set ImageView by local imageURI

### PR DESCRIPTION
**Pull request by ConrTG**
### Implementation Details

When I test to put image using FormElement.setValue(file.URI()), it only can use web URL

### Testing Details

I add if it is ImageView && value is String, set ImageURI

Hope it can help~ Thanks.

### CODE REVIEW

**Comment by TheJuki** [comment]
The value can also be a network URL. As part of #152, I will also need to be able to load a base64 image.

**Comment by TheJuki** [comment]
I just released [6.4.5](https://github.com/TheJuki/KFormMaster/releases/latest). Please update your dependency and let me know if change the value for the ImageView works for you.

**Comment by TheJuki** [comment]
Sorry. I just noticed that you are using URI. Picasso supports a URL with "file:" appended to the start of the string. So, please try that.

**Comment by ConrTG** [comment]
I try to use FormImageElement.setValue(file.toURI().toURL()) , but it still not working.

**Comment by TheJuki** [comment]
I just released [6.4.6](https://github.com/TheJuki/KFormMaster/releases/latest). Please update your dependency and let me know if changing the value for the ImageView works for you.  Previously it was trying to create a File object using the URL with "file:" in it. It did not work but Picasso will take that string.

So, `value = file.toURI().toURL().toString()` should work now.

**Comment by ConrTG** [comment]
Sorry for the late reply..
`value = file.toURI().toURL().toString()` works successfully.

I will delete this fork

Thank you so much~

**Pull request merged**
