### PR TITLE
Image Picker Element

### PR DESCRIPTION
**Pull request by soareseneves**
Implemented Image Picker Element, examples of usage on issue #119

### CODE REVIEW

**Comment by soareseneves** [comment]
Sorry for the mess 😆

**Comment by TheJuki** [comment]
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':form:processDebugUnitTestManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 15 cannot be smaller than version 19 declared in library [com.github.dhaval2404:imagepicker:1.2] /home/travis/.gradle/caches/transforms-2/files-2.1/97c37a81d10bc1734d59b18b4e00b3e8/AndroidManifest.xml as the library might be using APIs not available in 15
  	Suggestion: use a compatible library with a minSdk of at most 15,
  		or increase this project's minSdk version to at least 19,
  		or use tools:overrideLibrary="com.github.dhaval2404.imagepicker" to force usage (may lead to runtime failures)

**Comment by TheJuki** [comment]
The form build.gradle needs to be updated as well.

**Comment by soareseneves** [comment]
Done!

**Comment by TheJuki** [comment]
My poor code coverage. I'll work on the examples, tests, and documentation tonight.

**Pull request merged**
